[package]
name = "marco_polo_annotated"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "marco_polo_annotated"
path = "marco_polo_annotated.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
