[package]
name = "marco_polo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "marco_polo"
path = "marco_polo.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
