[package]
name = "lambda_passing_test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lambda_passing_test"
path = "lambda_passing_test.rs"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
