[package]
name = "test_itertools_comprehensive"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test_itertools_comprehensive"
path = "test_itertools_comprehensive.rs"

[dependencies]
itertools = "0.12"
