[package]
name = "lambda_advanced_test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lambda_advanced_test"
path = "lambda_advanced_test.rs"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
