[package]
name = "test_bisect_module"
version = "0.1.0"
edition = "2021"

[lib]
path = "test_bisect_module.rs"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
quickcheck = "1"
